# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
release:
  prerelease: auto
builds:
- env:
    - CGO_ENABLED=0
  main: cmd/mqtt2prometheus.go
  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - linux
    - darwin

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm64

archives:
- name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'

dockers:
  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}-amd64"
    skip_push: false


  - dockerfile: release/Dockerfile.scratch
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}-arm64"
    skip_push: false

docker_manifests:
  # Github Registry
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}
    skip_push: false
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}-arm64"

  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:latest
    skip_push: auto
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/mqtt2prometheus:{{ .Version }}-arm64"
